#!/bin/bash

DB_NAME=$1
MYSQL_PW="root"
DB_PASS=DB_NAME

mysql -u root -pMYSQL_PW <<<SQL
CREATE DATABASE IF NOT EXISTS $DB_NAME;
CREATE USER IF NOT EXISTS '$DB_NAME'@'localhost' IDENTIFIED BY $DB_PASS;
GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_NAME'@'localhost';
FLUSH PRIVILEGES;
SQL
